<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Diagnosis Report</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            padding: 30px;
        }

        .report-container {
            max-width: 800px;
            margin: auto;
            padding: 20px;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        /* Header */
        .header {
            display: flex;
            align-items: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #1a73e8;
            padding-bottom: 10px;
        }

        .header img {
            height: 70px;
            margin-right: 20px;
        }

        .header h1 {
            font-size: 2rem;
            color: #1a73e8;
            margin: 0;
        }

        /* Section Styles */
        .section-title {
            font-size: 1.5rem;
            color: white;
            background-color: #1a73e8;
            padding: 10px 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }

        /* Information and Diagnosis Styles */
        .info p, .diagnosis p {
            margin: 5px 0;
            font-size: 1rem;
        }

        p strong {
            color: #1a73e8;
        }

        .card {
            border: none;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }

        /* X-ray Image */
        .image-section img {
            max-height: 250px;
            width: auto;
            border: 1px solid #ddd;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        /* Footer */
        .footer {
            text-align: center;
            font-size: 0.8rem;
            color: #777;
            margin-top: 30px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }

    </style>
</head>
<body>
<div class="report-container">
    <!-- Header Section -->
    <div class="header">
        <img src="{{ public_path('images/bone fracture system logo.jpg') }}" alt="Bonescope Logo">
        <h1>BONESCOPE - Diagnosis Report</h1>
    </div>

    <!-- Patient Information Section -->
    <div class="section-title">Patient Information</div>
    <div class="card p-3">
        <div class="info">
            <p><strong>Name:</strong> {{ $patient_name ?? 'N/A' }}</p>
            <p><strong>Email:</strong> {{ $patient_email ?? 'N/A' }}</p>
            <p><strong>Date:</strong> {{ $date ?? 'N/A' }}</p>
            <p><strong>Age:</strong> {{ $patient_age ?? 'N/A' }}</p>
        </div>
    </div>

    <!-- Diagnosis Details Section -->
    <div class="section-title">Diagnosis Details</div>
    <div class="card p-3">
        <div class="diagnosis">
            <p><strong>Fracture Size:</strong> {{ $fracture_size ?? 'N/A' }} mm</p>
            <p><strong>Healing Time:</strong> {{ $healing_time ?? 'N/A' }}</p>
            <p><strong>Diagnosis:</strong> {{ $feedback ?? 'No feedback provided.' }}</p>
        </div>
    </div>


    <!-- Footer -->
    <div class="footer">
        <p>Generated by BONESCOPE - Advanced Bone Fracture Diagnosis System</p>
    </div>
</div>
</body>
</html>
